name: GitHub Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
  pull_request:
    branches:
      - main
  schedule:
    - cron: "15 6 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Event name is ${{ github.event_name }}"

      - run: echo "Branch is ${{ github.ref }}"

      - uses: actions/checkout@v4

      - run: ls -la
